#use_frameworks!

platform :ios, '8.0'

target 'GHLCrashGuard_Example' do
  pod 'GHLCrashGuard', :path => '../'
  pod 'JRSwizzle'
  pod 'BlocksKit'
  pod 'KVOController'
#  pod 'SafeKit'

  target 'GHLCrashGuard_Tests' do
    inherit! :search_paths

    
  end
end
