# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GHLDecouplingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GHLDecouplingDemo  
  pod 'GHLMediator', :path => '../GHLMediator'
  pod 'GHLRouter', :path => '../GHLRouter'
  pod 'GHLHome', :path => '../GHLHome'
  pod 'GHLSelectorService', :path => '../GHLSelectorService'

end
